# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/plugin/v1/execution_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/plugin/v1/execution_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto/plugin/v1/execution_engine.proto\x12\x0c\x63y.plugin.v1\"x\n\x17\x45xecuteInferenceRequest\x12\x1d\n\x15runtime_manifest_json\x18\x01 \x01(\t\x12\x1b\n\x13model_manifest_json\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x11\n\tstreaming\x18\x04 \x01(\x08\"/\n\x18\x45xecuteInferenceResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin.v1.execution_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEINFERENCEREQUEST']._serialized_start=56
  _globals['_EXECUTEINFERENCEREQUEST']._serialized_end=176
  _globals['_EXECUTEINFERENCERESPONSE']._serialized_start=178
  _globals['_EXECUTEINFERENCERESPONSE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
