# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/plugin/v1/gateway_filter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/plugin/v1/gateway_filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/plugin/v1/gateway_filter.proto\x12\x0c\x63y.plugin.v1\"\x88\x01\n\rFilterRequest\x12\x39\n\x07headers\x18\x01 \x03(\x0b\x32(.cy.plugin.v1.FilterRequest.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x0e\x46ilterResponse\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin.v1.gateway_filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTERREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_FILTERREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_FILTERREQUEST']._serialized_start=55
  _globals['_FILTERREQUEST']._serialized_end=191
  _globals['_FILTERREQUEST_HEADERSENTRY']._serialized_start=145
  _globals['_FILTERREQUEST_HEADERSENTRY']._serialized_end=191
  _globals['_FILTERRESPONSE']._serialized_start=193
  _globals['_FILTERRESPONSE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
