# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/plugin/v1/model_analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/plugin/v1/model_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/plugin/v1/model_analyzer.proto\x12\x0c\x63y.plugin.v1\"Q\n\x13\x41nalyzeModelRequest\x12\x1b\n\x13model_manifest_json\x18\x01 \x01(\t\x12\x1d\n\x15workload_request_json\x18\x02 \x01(\t\":\n\x14\x41nalyzeModelResponse\x12\x10\n\x08train_gb\x18\x01 \x01(\x01\x12\x10\n\x08infer_gb\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin.v1.model_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEMODELREQUEST']._serialized_start=54
  _globals['_ANALYZEMODELREQUEST']._serialized_end=135
  _globals['_ANALYZEMODELRESPONSE']._serialized_start=137
  _globals['_ANALYZEMODELRESPONSE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
