# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/plugin/v1/runtime_builder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/plugin/v1/runtime_builder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%proto/plugin/v1/runtime_builder.proto\x12\x0c\x63y.plugin.v1\"q\n\x13\x42uildRuntimeRequest\x12\x1d\n\x15workload_request_json\x18\x01 \x01(\t\x12\x1e\n\x16hardware_manifest_json\x18\x02 \x01(\t\x12\x1b\n\x13model_manifest_json\x18\x03 \x01(\t\"5\n\x14\x42uildRuntimeResponse\x12\x1d\n\x15runtime_manifest_json\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin.v1.runtime_builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUILDRUNTIMEREQUEST']._serialized_start=55
  _globals['_BUILDRUNTIMEREQUEST']._serialized_end=168
  _globals['_BUILDRUNTIMERESPONSE']._serialized_start=170
  _globals['_BUILDRUNTIMERESPONSE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
