# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/plugin/v1/storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/plugin/v1/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/plugin/v1/storage.proto\x12\x0c\x63y.plugin.v1\"D\n\x14StoreArtifactRequest\x12\x1e\n\x16\x61rtifact_manifest_json\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\",\n\x15StoreArtifactResponse\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\"+\n\x14\x46\x65tchArtifactRequest\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\"%\n\x15\x46\x65tchArtifactResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin.v1.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREARTIFACTREQUEST']._serialized_start=47
  _globals['_STOREARTIFACTREQUEST']._serialized_end=115
  _globals['_STOREARTIFACTRESPONSE']._serialized_start=117
  _globals['_STOREARTIFACTRESPONSE']._serialized_end=161
  _globals['_FETCHARTIFACTREQUEST']._serialized_start=163
  _globals['_FETCHARTIFACTREQUEST']._serialized_end=206
  _globals['_FETCHARTIFACTRESPONSE']._serialized_start=208
  _globals['_FETCHARTIFACTRESPONSE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
