# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import capability_execution_pb2 as capability__execution__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in capability_execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityExecutionServiceStub:
    """Frozen compatibility capability execution boundary.

    This service exposes capability semantics only. Resolution, activation,
    worker lifecycle, protocol framing, and process details remain inside the
    Platform implementation. Capability application events are also distinct
    from cyrene.core.v1 Kernel control events and are not written to the Kernel
    event history by this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeCapability = channel.unary_unary(
                '/cyrene.capability.v1.CapabilityExecutionService/InvokeCapability',
                request_serializer=capability__execution__pb2.InvokeCapabilityRequest.SerializeToString,
                response_deserializer=capability__execution__pb2.InvokeCapabilityResponse.FromString,
                _registered_method=True)
        self.InvokeCapabilityStream = channel.unary_stream(
                '/cyrene.capability.v1.CapabilityExecutionService/InvokeCapabilityStream',
                request_serializer=capability__execution__pb2.InvokeCapabilityRequest.SerializeToString,
                response_deserializer=capability__execution__pb2.CapabilityInvocationStreamItem.FromString,
                _registered_method=True)
        self.SubscribeCapabilityEvents = channel.unary_stream(
                '/cyrene.capability.v1.CapabilityExecutionService/SubscribeCapabilityEvents',
                request_serializer=capability__execution__pb2.SubscribeCapabilityEventsRequest.SerializeToString,
                response_deserializer=capability__execution__pb2.CapabilityEventStreamItem.FromString,
                _registered_method=True)


class CapabilityExecutionServiceServicer:
    """Frozen compatibility capability execution boundary.

    This service exposes capability semantics only. Resolution, activation,
    worker lifecycle, protocol framing, and process details remain inside the
    Platform implementation. Capability application events are also distinct
    from cyrene.core.v1 Kernel control events and are not written to the Kernel
    event history by this service.
    """

    def InvokeCapability(self, request, context):
        """Resolve, activate, invoke, and clean up one capability execution.
        The caller's native gRPC deadline and cancellation are the execution
        lifetime authority; there is no timeout field in this request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeCapabilityStream(self, request, context):
        """Resolve, activate, invoke, and clean up one capability execution while
        forwarding worker-produced typed chunks as they arrive. This additive
        method keeps the unary InvokeCapability contract unchanged for operations
        that do not expose a live result stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCapabilityEvents(self, request, context):
        """Start one live capability application-event stream. The server allocates
        the opaque subscription identity returned in stream items; callers do not
        choose or operate a worker subscription ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeCapability,
                    request_deserializer=capability__execution__pb2.InvokeCapabilityRequest.FromString,
                    response_serializer=capability__execution__pb2.InvokeCapabilityResponse.SerializeToString,
            ),
            'InvokeCapabilityStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InvokeCapabilityStream,
                    request_deserializer=capability__execution__pb2.InvokeCapabilityRequest.FromString,
                    response_serializer=capability__execution__pb2.CapabilityInvocationStreamItem.SerializeToString,
            ),
            'SubscribeCapabilityEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCapabilityEvents,
                    request_deserializer=capability__execution__pb2.SubscribeCapabilityEventsRequest.FromString,
                    response_serializer=capability__execution__pb2.CapabilityEventStreamItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyrene.capability.v1.CapabilityExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyrene.capability.v1.CapabilityExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityExecutionService:
    """Frozen compatibility capability execution boundary.

    This service exposes capability semantics only. Resolution, activation,
    worker lifecycle, protocol framing, and process details remain inside the
    Platform implementation. Capability application events are also distinct
    from cyrene.core.v1 Kernel control events and are not written to the Kernel
    event history by this service.
    """

    @staticmethod
    def InvokeCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyrene.capability.v1.CapabilityExecutionService/InvokeCapability',
            capability__execution__pb2.InvokeCapabilityRequest.SerializeToString,
            capability__execution__pb2.InvokeCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeCapabilityStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cyrene.capability.v1.CapabilityExecutionService/InvokeCapabilityStream',
            capability__execution__pb2.InvokeCapabilityRequest.SerializeToString,
            capability__execution__pb2.CapabilityInvocationStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCapabilityEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cyrene.capability.v1.CapabilityExecutionService/SubscribeCapabilityEvents',
            capability__execution__pb2.SubscribeCapabilityEventsRequest.SerializeToString,
            capability__execution__pb2.CapabilityEventStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
