# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training_backend.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'training_backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16training_backend.proto\x12\x0c\x63y.plugin.v1\"W\n\x16RunTrainingStepRequest\x12\x1d\n\x15runtime_manifest_json\x18\x01 \x01(\t\x12\x1e\n\x16training_revision_json\x18\x02 \x01(\t\";\n\x17RunTrainingStepResponse\x12 \n\x18\x63heckpoint_metadata_json\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNTRAININGSTEPREQUEST']._serialized_start=40
  _globals['_RUNTRAININGSTEPREQUEST']._serialized_end=127
  _globals['_RUNTRAININGSTEPRESPONSE']._serialized_start=129
  _globals['_RUNTRAININGSTEPRESPONSE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
