[package]
name = "cy-plugin-supervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
cy-plugin-protocol = { path = "../../../contracts/rust/cy-plugin-protocol" }
cy-local-transport = { path = "../cy-local-transport" }
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
thiserror = "1.0"
async-trait = "0.1"
tracing = "0.1"
chrono = "0.4"
uuid = { version = "1.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
cy-manifest = { version = "0.1.0", path = "../../../contracts/rust/cy-manifest" }
serde_json = "1.0.151"
cy-kernel-api = { path = "../cy-kernel-api" }

[dev-dependencies]
tempfile = "3.0"
