//! ┌─────────────────────────────────────────────────────────────────────┐
//! │  📄 user_code_secret.rs                                             │
//! │  Module: cy_workspace_fabric::user_code_secret                      │
//! │  Role: Versioned HMAC storage and verification for human user codes. │
//! │                                                                     │
//! │  模块职责：为人工输入的 user code 提供带版本的 HMAC 存储与校验。          │
//! └─────────────────────────────────────────────────────────────────────┘
//!
//! Keys are injected by the runtime configuration and are never generated by
//! this module. Keep every key version used by a live record until those
//! records expire or have been migrated.

use std::collections::BTreeMap;
use std::fmt;
use std::sync::Arc;

use hmac::{Hmac, Mac};
use sha2::Sha256;
use subtle::ConstantTimeEq;
use thiserror::Error;
use zeroize::Zeroizing;

type HmacSha256 = Hmac<Sha256>;

/// Maximum number of simultaneously readable user-code key versions.
///
/// This bounds per-code lookup work during key rotation.
pub const MAX_USER_CODE_KEY_VERSIONS: usize = 16;

const DOMAIN_SEPARATOR: &[u8] = b"cyrene-device-authorization:user-code:v1\0";
const USER_CODE_ALPHABET: &[u8] = b"ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const USER_CODE_LENGTH: usize = 12;

/// A stored HMAC and the key version needed to verify it.
///
/// The digest is deliberately redacted from debug output. Persistence adapters
/// can read the versioned storage parts, but must not log them.
#[derive(Clone, Copy)]
pub struct VersionedUserCodeDigest {
    key_version: u32,
    mac: [u8; 32],
}

impl VersionedUserCodeDigest {
    /// Reconstructs a digest loaded from storage.
    ///
    /// # Errors
    /// Returns [`UserCodeSecretError::InvalidKeyVersion`] for reserved version
    /// zero. The digest bytes are opaque and must not be logged.
    pub fn from_storage_parts(
        key_version: u32,
        mac: [u8; 32],
    ) -> Result<Self, UserCodeSecretError> {
        if key_version == 0 {
            return Err(UserCodeSecretError::InvalidKeyVersion);
        }
        Ok(Self { key_version, mac })
    }

    /// Returns the key version and opaque MAC bytes for persistence.
    pub fn storage_parts(&self) -> (u32, &[u8; 32]) {
        (self.key_version, &self.mac)
    }

    /// Returns the public key-version identifier.
    pub fn key_version(&self) -> u32 {
        self.key_version
    }
}

impl fmt::Debug for VersionedUserCodeDigest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("VersionedUserCodeDigest")
            .field("key_version", &self.key_version)
            .field("mac", &"[REDACTED]")
            .finish()
    }
}

impl PartialEq for VersionedUserCodeDigest {
    fn eq(&self, other: &Self) -> bool {
        let mac_matches = bool::from(self.mac.ct_eq(&other.mac));
        self.key_version == other.key_version && mac_matches
    }
}

impl Eq for VersionedUserCodeDigest {}

/// Errors from key-ring configuration, code validation, or digest verification.
#[derive(Debug, Error, Clone, Copy, PartialEq, Eq)]
pub enum UserCodeSecretError {
    #[error("user-code key ring must not be empty")]
    EmptyKeyRing,
    #[error("active user-code key version is not configured")]
    ActiveKeyUnavailable,
    #[error("user-code key version zero is reserved")]
    InvalidKeyVersion,
    #[error("user-code key ring exceeds the supported version limit")]
    TooManyKeyVersions,
    #[error("user-code key version is unavailable: {version}")]
    MissingKeyVersion { version: u32 },
    #[error("normalized user code has an invalid format")]
    InvalidUserCode,
    #[error("HMAC-SHA256 initialization failed")]
    HmacInitializationFailed,
}

struct UserCodeKeyRingInner {
    active_version: u32,
    keys: BTreeMap<u32, Zeroizing<[u8; 32]>>,
}

/// Server-held, versioned HMAC-SHA256 keys for user-code storage.
///
/// Construct this from stable secret configuration. Rotations add the new key
/// version and select it as active while retaining old versions for reads.
/// This type has no default or random-key constructor so restart-stable keys
/// must be supplied by the caller.
#[derive(Clone)]
pub struct UserCodeKeyRing {
    inner: Arc<UserCodeKeyRingInner>,
}

impl UserCodeKeyRing {
    /// Creates a key ring from runtime-injected 256-bit keys.
    ///
    /// Version zero is reserved. At most
    /// [`MAX_USER_CODE_KEY_VERSIONS`] versions may be configured.
    ///
    /// # Errors
    /// Returns an error for an empty ring, an invalid version, too many keys,
    /// or an active version that is absent. Key material is zeroized when this
    /// key ring is dropped.
    pub fn new(
        active_version: u32,
        keys: BTreeMap<u32, [u8; 32]>,
    ) -> Result<Self, UserCodeSecretError> {
        // Move every supplied key into zeroizing storage before validating so
        // error paths also clear key material already accepted by this method.
        let mut secret_keys = BTreeMap::new();
        let mut has_invalid_version = active_version == 0;
        for (version, key) in keys {
            has_invalid_version |= version == 0;
            secret_keys.insert(version, Zeroizing::new(key));
        }

        if has_invalid_version {
            return Err(UserCodeSecretError::InvalidKeyVersion);
        }
        if secret_keys.is_empty() {
            return Err(UserCodeSecretError::EmptyKeyRing);
        }
        if secret_keys.len() > MAX_USER_CODE_KEY_VERSIONS {
            return Err(UserCodeSecretError::TooManyKeyVersions);
        }
        if !secret_keys.contains_key(&active_version) {
            return Err(UserCodeSecretError::ActiveKeyUnavailable);
        }

        Ok(Self {
            inner: Arc::new(UserCodeKeyRingInner {
                active_version,
                keys: secret_keys,
            }),
        })
    }

    /// Returns the currently selected version for newly stored user codes.
    pub fn active_version(&self) -> u32 {
        self.inner.active_version
    }

    /// Returns configured key versions in ascending order.
    pub fn key_versions(&self) -> impl ExactSizeIterator<Item = u32> + '_ {
        self.inner.keys.keys().copied()
    }

    /// Fails closed if durable records reference a key version absent here.
    ///
    /// Call this during service startup using the versions recorded by the
    /// backing store. This lets the service detect a missing historical key
    /// before user-code lookups silently stop matching those records.
    pub fn require_versions(
        &self,
        required_versions: impl IntoIterator<Item = u32>,
    ) -> Result<(), UserCodeSecretError> {
        for version in required_versions {
            if version == 0 {
                return Err(UserCodeSecretError::InvalidKeyVersion);
            }
            if !self.inner.keys.contains_key(&version) {
                return Err(UserCodeSecretError::MissingKeyVersion { version });
            }
        }
        Ok(())
    }

    /// Computes the digest used for a newly persisted user code.
    ///
    /// `normalized_code` must already use the device-authorization user-code
    /// alphabet and contain exactly twelve ASCII characters.
    pub fn digest_for_storage(
        &self,
        normalized_code: &str,
    ) -> Result<VersionedUserCodeDigest, UserCodeSecretError> {
        validate_normalized_code(normalized_code)?;
        let key = self.inner.keys.get(&self.inner.active_version).ok_or(
            UserCodeSecretError::MissingKeyVersion {
                version: self.inner.active_version,
            },
        )?;
        let mac = compute_mac(&key[..], self.inner.active_version, normalized_code)?;
        Ok(VersionedUserCodeDigest {
            key_version: self.inner.active_version,
            mac,
        })
    }

    /// Computes lookup candidates for every configured key version.
    ///
    /// Storage should query all returned `(version, MAC)` pairs together. Do
    /// not stop after the first version or write candidates to logs; retaining
    /// old keys is required to look up records created before a rotation.
    pub fn lookup_candidates(
        &self,
        normalized_code: &str,
    ) -> Result<Vec<VersionedUserCodeDigest>, UserCodeSecretError> {
        validate_normalized_code(normalized_code)?;
        self.inner
            .keys
            .iter()
            .map(|(version, key)| {
                Ok(VersionedUserCodeDigest {
                    key_version: *version,
                    mac: compute_mac(&key[..], *version, normalized_code)?,
                })
            })
            .collect()
    }

    /// Verifies a stored digest with its recorded key version.
    ///
    /// The MAC comparison uses the HMAC library's constant-time verification.
    /// A missing key version is an error, never an ordinary mismatch.
    pub fn verify(
        &self,
        normalized_code: &str,
        stored: &VersionedUserCodeDigest,
    ) -> Result<bool, UserCodeSecretError> {
        validate_normalized_code(normalized_code)?;
        let key = self.inner.keys.get(&stored.key_version).ok_or(
            UserCodeSecretError::MissingKeyVersion {
                version: stored.key_version,
            },
        )?;
        let mac = new_mac(&key[..], stored.key_version, normalized_code)?;
        Ok(mac.verify_slice(&stored.mac).is_ok())
    }
}

impl fmt::Debug for UserCodeKeyRing {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("UserCodeKeyRing")
            .field("active_version", &self.inner.active_version)
            .field(
                "configured_versions",
                &self.inner.keys.keys().collect::<Vec<_>>(),
            )
            .field("key_material", &"[REDACTED]")
            .finish()
    }
}

fn validate_normalized_code(code: &str) -> Result<(), UserCodeSecretError> {
    if code.len() != USER_CODE_LENGTH
        || !code.bytes().all(|byte| USER_CODE_ALPHABET.contains(&byte))
    {
        return Err(UserCodeSecretError::InvalidUserCode);
    }
    Ok(())
}

fn compute_mac(
    key: &[u8],
    key_version: u32,
    normalized_code: &str,
) -> Result<[u8; 32], UserCodeSecretError> {
    let mac = new_mac(key, key_version, normalized_code)?;
    let bytes: [u8; 32] = mac.finalize().into_bytes().into();
    Ok(bytes)
}

fn new_mac(
    key: &[u8],
    key_version: u32,
    normalized_code: &str,
) -> Result<HmacSha256, UserCodeSecretError> {
    let mut mac = HmacSha256::new_from_slice(key)
        .map_err(|_| UserCodeSecretError::HmacInitializationFailed)?;
    mac.update(DOMAIN_SEPARATOR);
    mac.update(&key_version.to_be_bytes());
    mac.update(&(normalized_code.len() as u64).to_be_bytes());
    mac.update(normalized_code.as_bytes());
    Ok(mac)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key_ring(active_version: u32, keys: &[(u32, [u8; 32])]) -> UserCodeKeyRing {
        UserCodeKeyRing::new(active_version, keys.iter().copied().collect())
            .expect("test key ring is valid")
    }

    #[test]
    fn stable_injected_keys_produce_restart_stable_versioned_digests() {
        let first_process = key_ring(4, &[(4, [0x31; 32])]);
        let restarted_process = key_ring(4, &[(4, [0x31; 32])]);

        let first = first_process
            .digest_for_storage("ABCD2345EFGH")
            .expect("valid normalized code");
        let after_restart = restarted_process
            .digest_for_storage("ABCD2345EFGH")
            .expect("valid normalized code");

        assert_eq!(first, after_restart);
        assert_eq!(first.key_version(), 4);
        assert!(restarted_process
            .verify("ABCD2345EFGH", &first)
            .expect("configured key version"));
        assert!(!restarted_process
            .verify("ABCD2345EFGJ", &first)
            .expect("configured key version"));
    }

    #[test]
    fn key_rotation_reads_old_records_and_writes_with_the_active_version() {
        let old_ring = key_ring(7, &[(7, [0x47; 32])]);
        let old_digest = old_ring
            .digest_for_storage("ABCD2345EFGH")
            .expect("valid normalized code");
        let rotated_ring = key_ring(8, &[(7, [0x47; 32]), (8, [0x58; 32])]);

        let candidates = rotated_ring
            .lookup_candidates("ABCD2345EFGH")
            .expect("valid normalized code");
        assert_eq!(candidates.len(), 2);
        assert_eq!(candidates[0].key_version(), 7);
        assert_eq!(candidates[1].key_version(), 8);
        assert!(rotated_ring
            .verify("ABCD2345EFGH", &old_digest)
            .expect("old key remains configured"));
        assert_eq!(
            rotated_ring
                .digest_for_storage("ABCD2345EFGH")
                .expect("valid normalized code")
                .key_version(),
            8
        );
        assert_eq!(rotated_ring.require_versions([7, 8]), Ok(()));
    }

    #[test]
    fn key_version_is_included_in_the_mac_transcript() {
        let ring = key_ring(8, &[(7, [0x77; 32]), (8, [0x77; 32])]);
        let candidates = ring
            .lookup_candidates("ABCD2345EFGH")
            .expect("valid normalized code");

        assert_ne!(candidates[0], candidates[1]);
    }

    #[test]
    fn missing_historical_key_fails_closed_instead_of_becoming_a_mismatch() {
        let ring = key_ring(2, &[(2, [0x22; 32])]);
        let stored = VersionedUserCodeDigest::from_storage_parts(1, [0x11; 32])
            .expect("nonzero storage version");

        assert_eq!(
            ring.verify("ABCD2345EFGH", &stored),
            Err(UserCodeSecretError::MissingKeyVersion { version: 1 })
        );
        assert_eq!(
            ring.require_versions([1]),
            Err(UserCodeSecretError::MissingKeyVersion { version: 1 })
        );
    }

    #[test]
    fn code_and_key_ring_boundaries_are_checked() {
        let ring = key_ring(1, &[(1, [0x11; 32])]);

        for invalid in ["", "ABCD2345EFG", "ABCD2345EFGI", "ABCD2345EFG-", "你好"] {
            assert_eq!(
                ring.digest_for_storage(invalid),
                Err(UserCodeSecretError::InvalidUserCode)
            );
        }
        assert_eq!(
            UserCodeKeyRing::new(1, BTreeMap::new()).map(|_| ()),
            Err(UserCodeSecretError::EmptyKeyRing)
        );
        assert_eq!(
            UserCodeKeyRing::new(2, BTreeMap::from([(1, [0x11; 32])])).map(|_| ()),
            Err(UserCodeSecretError::ActiveKeyUnavailable)
        );
        assert_eq!(
            UserCodeKeyRing::new(0, BTreeMap::from([(0, [0x11; 32])])).map(|_| ()),
            Err(UserCodeSecretError::InvalidKeyVersion)
        );
        let too_many_keys = (1..=MAX_USER_CODE_KEY_VERSIONS as u32 + 1)
            .map(|version| (version, [version as u8; 32]))
            .collect();
        assert_eq!(
            UserCodeKeyRing::new(1, too_many_keys).map(|_| ()),
            Err(UserCodeSecretError::TooManyKeyVersions)
        );
        assert_eq!(
            VersionedUserCodeDigest::from_storage_parts(0, [0; 32]).map(|_| ()),
            Err(UserCodeSecretError::InvalidKeyVersion)
        );
    }

    #[test]
    fn debug_output_redacts_keys_and_macs() {
        let key = [0xab; 32];
        let ring = key_ring(3, &[(3, key)]);
        let digest = ring
            .digest_for_storage("ABCD2345EFGH")
            .expect("valid normalized code");
        let key_hex = key
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();

        assert!(!format!("{ring:?}").contains(&key_hex));
        assert!(format!("{digest:?}").contains("REDACTED"));
    }
}
