apiVersion: v1
kind: Service
metadata:
  name: astrbot-web
  namespace: astrbot-ns
  labels:
    app: astrbot-stack
spec:
  type: ClusterIP
  selector:
    app: astrbot-stack
  ports:
    - name: web
      port: 8080
      targetPort: dotnet-host
