# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/plugin/v1/compat_rule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/plugin/v1/compat_rule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/plugin/v1/compat_rule.proto\x12\x0c\x63y.plugin.v1\"s\n\x15\x45valuateCompatRequest\x12\x1e\n\x16hardware_manifest_json\x18\x01 \x01(\t\x12\x1b\n\x13model_manifest_json\x18\x02 \x01(\t\x12\x1d\n\x15workload_request_json\x18\x03 \x01(\t\"1\n\x16\x45valuateCompatResponse\x12\x17\n\x0fwhy_report_json\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin.v1.compat_rule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATECOMPATREQUEST']._serialized_start=51
  _globals['_EVALUATECOMPATREQUEST']._serialized_end=166
  _globals['_EVALUATECOMPATRESPONSE']._serialized_start=168
  _globals['_EVALUATECOMPATRESPONSE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
