// ╔══════════════════════════════════════════════════════════════════════╗
// ║ 📄 File: framework/crates/cy-capability-execution-service/src/lib.rs
// ║ Module: CYRENE Platform
// ║ Role: Rust implementation, protocol, or conformance test for this repository boundary.
// ║
// ║ 模块：CYRENE Platform
// ║ 职责：Rust 实现、协议或一致性测试。
// ╚══════════════════════════════════════════════════════════════════════╝
//! Product-facing, language-neutral capability execution service.
//!
//! The service is intentionally a small adapter around the existing Platform
//! resolver and generic worker runtime. Products see only capability identity,
//! `google.protobuf.Any` payloads, and stable execution/stream outcomes. The
//! `cy.plugin.v1` envelope, worker subscription IDs, process handles, and
//! executable details remain private to this crate and `cy-platform-api`.

mod binding_config;

pub use binding_config::{
    ConfigurationError, ConfiguredBinding, build_service, load_bindings, load_manifest,
};

use std::{
    collections::HashMap,
    pin::Pin,
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, AtomicUsize, Ordering},
    },
    time::Duration,
};

use cy_manifest::{
    CapabilityId, CapabilityInterfaceVersion, ExecutionMode, PluginManifest, PluginRequirement,
};
use cy_platform_api::{
    ApplicationEventError, ApplicationEventStreamEndReason, ApplicationEventStreamTermination,
    AtomicCancellationToken, CancellationToken, CapabilityRegistry, CapabilityResolutionError,
    CapabilityWorkerActivator, DEFAULT_APPLICATION_EVENT_BUFFER_CAPACITY,
    MAX_APPLICATION_EVENT_BUFFER_CAPACITY, WorkerActivationOptions, WorkerApplicationEvent,
    WorkerInvocationResult, WorkerTerminalError,
};
use cy_proto::capability_v1::{
    CapabilityApplicationEvent, CapabilityEventStreamEnd, CapabilityEventStreamItem,
    CapabilityExecutionError, InvokeCapabilityRequest, InvokeCapabilityResponse,
    SubscribeCapabilityEventsRequest, capability_event_stream_item, capability_execution_error,
    capability_execution_service_server::{
        CapabilityExecutionService as CapabilityExecutionServiceTrait,
        CapabilityExecutionServiceServer,
    },
};
use futures_core::Stream;
use prost_types::Any;
use tokio::sync::mpsc::{self, OwnedPermit, Sender, error::TrySendError};
use tokio_stream::wrappers::ReceiverStream;
use tonic::{Request, Response, Status, metadata::MetadataMap};
use uuid::Uuid;

/// The fixed type URL used when the legacy worker wire has opaque bytes but no
/// Product-facing protobuf type URL. Typed capability implementations may use
/// their own `Any.type_url`; this adapter never invents a domain schema.
pub const OPAQUE_PAYLOAD_TYPE_URL: &str = "type.cyrene.io/cyrene.capability.v1.OpaquePayload";

/// Product-facing stream type generated by the server-streaming RPC.
pub type CapabilityEventStream =
    Pin<Box<dyn Stream<Item = Result<CapabilityEventStreamItem, Status>> + Send + 'static>>;

/// Platform-owned safety and buffering configuration. None of these values
/// are caller-controlled API fields. The gRPC deadline remains the caller's
/// timeout authority; `WorkerActivationOptions::default_invoke_timeout` is
/// only the bounded safety ceiling used when a client omits a deadline.
#[derive(Debug, Clone)]
pub struct CapabilityExecutionConfig {
    pub worker_options: WorkerActivationOptions,
    pub application_event_buffer_capacity: usize,
    pub event_poll_interval: Duration,
    pub cancellation_drain_timeout: Duration,
}

impl Default for CapabilityExecutionConfig {
    fn default() -> Self {
        Self {
            worker_options: WorkerActivationOptions::default(),
            application_event_buffer_capacity: DEFAULT_APPLICATION_EVENT_BUFFER_CAPACITY,
            event_poll_interval: Duration::from_millis(20),
            cancellation_drain_timeout: Duration::from_secs(3),
        }
    }
}

impl CapabilityExecutionConfig {
    pub fn with_application_event_buffer_capacity(
        mut self,
        capacity: usize,
    ) -> Result<Self, String> {
        if !(1..=MAX_APPLICATION_EVENT_BUFFER_CAPACITY).contains(&capacity) {
            return Err(format!(
                "application-event buffer capacity must be between 1 and {}",
                MAX_APPLICATION_EVENT_BUFFER_CAPACITY
            ));
        }
        self.application_event_buffer_capacity = capacity;
        Ok(self)
    }
}

#[derive(Debug, Clone)]
struct ResolvedExecution {
    manifest: PluginManifest,
    worker_options: WorkerActivationOptions,
    source_id: String,
    binding_id: Option<String>,
}

/// Stable public identity carried by every terminal stream item.
///
/// Keeping this context together prevents the terminal-item constructor from
/// growing a long, order-sensitive argument list as new runtime facts are
/// added.
#[derive(Debug, Clone)]
struct StreamEndContext {
    subscription_id: String,
    capability: String,
    source_id: String,
    binding_id: String,
}

#[derive(Debug)]
struct SubscriptionTask {
    public_subscription_id: String,
    capability: String,
    execution: ResolvedExecution,
    filter_payload: Vec<u8>,
    ack_timeout: Duration,
    token: Arc<AtomicCancellationToken>,
    sender: Sender<Result<CapabilityEventStreamItem, Status>>,
    terminal_permit: OwnedPermit<Result<CapabilityEventStreamItem, Status>>,
}

#[derive(Debug)]
struct ActiveOperationGuard {
    id: String,
    token: Arc<AtomicCancellationToken>,
    active: Arc<Mutex<HashMap<String, Arc<AtomicCancellationToken>>>>,
}

#[derive(Debug)]
struct RunningTaskGuard(Arc<AtomicUsize>);

impl Drop for RunningTaskGuard {
    fn drop(&mut self) {
        self.0.fetch_sub(1, Ordering::SeqCst);
    }
}

impl Drop for ActiveOperationGuard {
    fn drop(&mut self) {
        self.token.cancel();
        if let Ok(mut active) = self.active.lock() {
            active.remove(&self.id);
        }
    }
}

/// Generic Platform capability execution service.
///
/// Resolution and worker activation are transparent: the service selects an
/// exact registered capability interface, activates the selected worker with
/// the existing `CapabilityWorkerActivator`, and cleans up the client when the
/// invocation or live subscription ends. `ServiceSupervisor` remains the
/// owner of this service process's restart/backoff policy; this service owns
/// only request-scoped worker sessions and does not restart them.
#[derive(Clone, Debug)]
pub struct CapabilityExecutionService {
    registry: Arc<CapabilityRegistry>,
    config: Arc<CapabilityExecutionConfig>,
    provider_worker_options: Arc<HashMap<(String, String), WorkerActivationOptions>>,
    binding_worker_options: Arc<HashMap<String, WorkerActivationOptions>>,
    active: Arc<Mutex<HashMap<String, Arc<AtomicCancellationToken>>>>,
    running_tasks: Arc<AtomicUsize>,
    stopping: Arc<AtomicBool>,
}

impl CapabilityExecutionService {
    /// Construct a service over an immutable snapshot of the canonical
    /// Platform capability registry.
    pub fn new(registry: CapabilityRegistry, mut config: CapabilityExecutionConfig) -> Self {
        // The config is Platform-owned, but keep the hard bound true even
        // when an embedding process constructs the struct directly instead of
        // using the validating builder.
        config.application_event_buffer_capacity = config
            .application_event_buffer_capacity
            .clamp(1, MAX_APPLICATION_EVENT_BUFFER_CAPACITY);
        Self {
            registry: Arc::new(registry),
            config: Arc::new(config),
            provider_worker_options: Arc::new(HashMap::new()),
            binding_worker_options: Arc::new(HashMap::new()),
            active: Arc::new(Mutex::new(HashMap::new())),
            running_tasks: Arc::new(AtomicUsize::new(0)),
            stopping: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Associate activation settings with one exact provider release. This is
    /// configuration of the generic worker runtime, not a second manifest or
    /// a Product-facing provider selector.
    pub fn with_provider_worker_options(
        mut self,
        plugin_id: impl Into<String>,
        plugin_version: impl Into<String>,
        options: WorkerActivationOptions,
    ) -> Self {
        let mut options_by_provider = (*self.provider_worker_options).clone();
        options_by_provider.insert((plugin_id.into(), plugin_version.into()), options);
        self.provider_worker_options = Arc::new(options_by_provider);
        self
    }

    /// Associate activation settings with one exact configured binding. The
    /// binding ID is stable configuration identity; these options are only
    /// Platform runtime details and are never part of the Product contract.
    pub fn with_binding_worker_options(
        mut self,
        binding_id: impl Into<String>,
        options: WorkerActivationOptions,
    ) -> Self {
        let mut options_by_binding = (*self.binding_worker_options).clone();
        options_by_binding.insert(binding_id.into(), options);
        self.binding_worker_options = Arc::new(options_by_binding);
        self
    }

    pub fn registry(&self) -> &CapabilityRegistry {
        self.registry.as_ref()
    }

    pub fn configured_event_buffer_capacity(&self) -> usize {
        self.config.application_event_buffer_capacity
    }

    /// Stop all request-scoped sessions. The process supervisor remains the
    /// authoritative owner of restarting the service process; this method is
    /// only the service's bounded graceful-drain hook.
    pub async fn shutdown(&self) {
        self.stopping.store(true, Ordering::SeqCst);
        if let Ok(active) = self.active.lock() {
            for token in active.values() {
                token.cancel();
            }
        }

        let deadline = tokio::time::Instant::now()
            + self.config.cancellation_drain_timeout
            + self.config.worker_options.shutdown_grace_period;
        while self.running_task_count() > 0 && tokio::time::Instant::now() < deadline {
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    }

    pub fn active_count(&self) -> usize {
        self.active.lock().map(|active| active.len()).unwrap_or(0)
    }

    pub fn running_task_count(&self) -> usize {
        self.running_tasks.load(Ordering::SeqCst)
    }

    fn start_task(&self) -> RunningTaskGuard {
        self.running_tasks.fetch_add(1, Ordering::SeqCst);
        RunningTaskGuard(Arc::clone(&self.running_tasks))
    }

    fn register_operation(&self) -> ActiveOperationGuard {
        let id = Uuid::new_v4().to_string();
        let token = Arc::new(AtomicCancellationToken::new());
        if let Ok(mut active) = self.active.lock() {
            active.insert(id.clone(), token.clone());
        }
        ActiveOperationGuard {
            id,
            token,
            active: Arc::clone(&self.active),
        }
    }

    fn resolve_worker(
        &self,
        capability: &str,
        interface_version: &str,
        binding_id: Option<&str>,
    ) -> Result<ResolvedExecution, ApiError> {
        if capability.trim().is_empty() || interface_version.trim().is_empty() {
            return Err(ApiError::new(
                capability_execution_error::Code::InvalidRequest,
                "capability and interface_version are required",
            ));
        }

        let capability_id = CapabilityId::new(capability.to_string()).map_err(|error| {
            ApiError::new(
                capability_execution_error::Code::InvalidRequest,
                error.to_string(),
            )
        })?;
        let interface =
            CapabilityInterfaceVersion::new(interface_version.to_string()).map_err(|error| {
                ApiError::new(
                    capability_execution_error::Code::InvalidRequest,
                    error.to_string(),
                )
            })?;
        let requirement = PluginRequirement {
            capability: capability_id,
            interface_version: interface,
            execution_modes: vec![ExecutionMode::Worker],
        };
        let resolved = self
            .registry
            .resolver()
            .resolve_target(&requirement, binding_id)
            .map_err(ApiError::from_resolution)?;
        let manifest = self
            .registry
            .manifest_for(
                &resolved.capability.plugin.id,
                &resolved.capability.plugin_version.version,
            )
            .ok_or_else(|| {
                ApiError::new(
                    capability_execution_error::Code::CapabilityUnavailable,
                    "resolved capability provider is no longer registered",
                )
            })?;
        let worker_options = self
            .binding_worker_options
            .get(resolved.binding_id.as_deref().unwrap_or_default())
            .cloned()
            .or_else(|| {
                self.provider_worker_options
                    .get(&(
                        resolved.capability.plugin.id.clone(),
                        resolved.capability.plugin_version.version.clone(),
                    ))
                    .cloned()
            })
            .unwrap_or_else(|| self.config.worker_options.clone());

        Ok(ResolvedExecution {
            manifest,
            worker_options,
            source_id: resolved.capability.plugin.id,
            binding_id: resolved.binding_id,
        })
    }

    fn invoke_timeout(
        metadata: &MetadataMap,
        worker_options: &WorkerActivationOptions,
    ) -> Result<Duration, ApiError> {
        let native_deadline = parse_grpc_timeout(metadata).map_err(|message| {
            ApiError::new(capability_execution_error::Code::InvalidRequest, message)
        })?;
        Ok(native_deadline.unwrap_or(worker_options.default_invoke_timeout))
    }

    fn invoke_response_error(error: ApiError) -> InvokeCapabilityResponse {
        InvokeCapabilityResponse {
            result: Some(
                cy_proto::capability_v1::invoke_capability_response::Result::Error(
                    error.into_wire(),
                ),
            ),
        }
    }

    fn stream_for_terminal(
        subscription_id: String,
        capability: String,
        source_id: String,
        binding_id: String,
        error: ApiError,
        reason: i32,
    ) -> CapabilityEventStream {
        let (sender, receiver) = mpsc::channel(1);
        let context = StreamEndContext {
            subscription_id,
            capability,
            source_id,
            binding_id,
        };
        let item = context.item(0, reason, error.message.clone(), Some(error.into_wire()));
        let _ = sender.try_send(Ok(item));
        Box::pin(ReceiverStream::new(receiver))
    }

    fn stream_for_clean_end(
        subscription_id: String,
        capability: String,
        reason: i32,
        message: impl Into<String>,
    ) -> CapabilityEventStream {
        let (sender, receiver) = mpsc::channel(1);
        let context = StreamEndContext {
            subscription_id,
            capability,
            source_id: String::new(),
            binding_id: String::new(),
        };
        let item = context.item(0, reason, message, None);
        let _ = sender.try_send(Ok(item));
        Box::pin(ReceiverStream::new(receiver))
    }

    async fn invoke_internal(
        &self,
        request: InvokeCapabilityRequest,
        metadata: &MetadataMap,
    ) -> InvokeCapabilityResponse {
        if self.stopping.load(Ordering::SeqCst) {
            return Self::invoke_response_error(ApiError::new(
                capability_execution_error::Code::CapabilityUnavailable,
                "capability execution service is shutting down",
            ));
        }
        if request.method.trim().is_empty() {
            return Self::invoke_response_error(ApiError::new(
                capability_execution_error::Code::InvalidRequest,
                "method is required",
            ));
        }
        let Some(request_payload) = request.request else {
            return Self::invoke_response_error(ApiError::new(
                capability_execution_error::Code::InvalidRequest,
                "request Any is required",
            ));
        };
        if request_payload.type_url.trim().is_empty() {
            return Self::invoke_response_error(ApiError::new(
                capability_execution_error::Code::InvalidRequest,
                "request Any.type_url is required",
            ));
        }

        let binding_id = request
            .binding_id
            .as_deref()
            .filter(|binding_id| !binding_id.trim().is_empty());
        let execution = match self.resolve_worker(
            &request.capability,
            &request.interface_version,
            binding_id,
        ) {
            Ok(execution) => execution,
            Err(error) => return Self::invoke_response_error(error),
        };
        let timeout = match Self::invoke_timeout(metadata, &execution.worker_options) {
            Ok(timeout) => timeout,
            Err(error) => return Self::invoke_response_error(error),
        };
        if timeout.is_zero() {
            return Self::invoke_response_error(ApiError::new(
                capability_execution_error::Code::Timeout,
                "gRPC deadline has expired",
            ));
        }

        let guard = self.register_operation();
        let cancellation = Arc::clone(&guard.token);
        let capability = request.capability.clone();
        let method = request.method.clone();
        let request_type_url = request_payload.type_url;
        let payload = request_payload.value;
        let manifest = execution.manifest;
        let worker_options = execution.worker_options;
        let worker_timeout = timeout;
        let task_guard = self.start_task();
        let join = tokio::task::spawn_blocking(move || {
            let _task_guard = task_guard;
            let mut client =
                CapabilityWorkerActivator::activate_from_manifest(&manifest, &worker_options)?;
            let result = client.invoke_typed_with_request_type_url(
                &capability,
                &method,
                &payload,
                &request_type_url,
                worker_timeout,
                cancellation.as_ref(),
            );
            let shutdown_result = client.shutdown(worker_options.shutdown_grace_period);
            match result {
                Ok(value) => {
                    shutdown_result?;
                    Ok(value)
                }
                Err(error) => {
                    let _ = shutdown_result;
                    Err(error)
                }
            }
        });

        // Tonic owns the native RPC deadline. If that deadline or caller
        // cancellation drops this future, ActiveOperationGuard cancels the
        // blocking task and CapabilityWorkerClient sends the canonical
        // worker Cancel. The timeout passed below is the same native
        // deadline-derived value (or the Platform fallback when no deadline
        // was supplied), not a second Product-facing timeout authority.
        let result = join
            .await
            .map_err(|error| WorkerTerminalError::CapabilityExecutionFailure(error.to_string()))
            .and_then(|result| result);
        match result {
            Ok(value) => InvokeCapabilityResponse {
                result: Some(
                    cy_proto::capability_v1::invoke_capability_response::Result::Response(
                        response_any(&request.capability, &request.method, value),
                    ),
                ),
            },
            Err(error) => Self::invoke_response_error(ApiError::from_worker(error)),
        }
    }

    fn start_subscription(
        &self,
        request: SubscribeCapabilityEventsRequest,
        metadata: &MetadataMap,
    ) -> CapabilityEventStream {
        let subscription_id = Uuid::new_v4().to_string();
        if self.stopping.load(Ordering::SeqCst) {
            return Self::stream_for_clean_end(
                subscription_id,
                request.capability,
                stream_reason::NORMAL_COMPLETION,
                "capability execution service is shutting down",
            );
        }
        if let Some(filter) = request.filter.as_ref()
            && filter.type_url.trim().is_empty()
        {
            return Self::stream_for_terminal(
                subscription_id,
                request.capability,
                String::new(),
                String::new(),
                ApiError::new(
                    capability_execution_error::Code::InvalidRequest,
                    "filter Any.type_url is required when filter is present",
                ),
                stream_reason::UNSPECIFIED,
            );
        }
        let binding_id = request
            .binding_id
            .as_deref()
            .filter(|binding_id| !binding_id.trim().is_empty());
        let execution = match self.resolve_worker(
            &request.capability,
            &request.interface_version,
            binding_id,
        ) {
            Ok(execution) => execution,
            Err(error) => {
                let reason = stream_reason_for_error(error.code);
                return Self::stream_for_terminal(
                    subscription_id,
                    request.capability,
                    String::new(),
                    String::new(),
                    error,
                    reason,
                );
            }
        };
        let ack_timeout = match parse_grpc_timeout(metadata) {
            Ok(Some(timeout)) => timeout.min(execution.worker_options.handshake_timeout),
            Ok(None) => execution.worker_options.handshake_timeout,
            Err(message) => {
                return Self::stream_for_terminal(
                    subscription_id,
                    request.capability,
                    execution.source_id.clone(),
                    execution.binding_id.clone().unwrap_or_default(),
                    ApiError::new(capability_execution_error::Code::InvalidRequest, message),
                    stream_reason::UNSPECIFIED,
                );
            }
        };
        if ack_timeout.is_zero() {
            return Self::stream_for_terminal(
                subscription_id,
                request.capability,
                execution.source_id.clone(),
                execution.binding_id.clone().unwrap_or_default(),
                ApiError::new(
                    capability_execution_error::Code::Timeout,
                    "gRPC deadline has expired",
                ),
                stream_reason::UNSPECIFIED,
            );
        }

        let buffer_capacity = self.config.application_event_buffer_capacity;
        let (sender, receiver) = mpsc::channel(buffer_capacity + 1);
        let terminal_permit = match sender.clone().try_reserve_owned() {
            Ok(permit) => permit,
            Err(_) => {
                return Self::stream_for_terminal(
                    subscription_id,
                    request.capability,
                    execution.source_id.clone(),
                    execution.binding_id.clone().unwrap_or_default(),
                    ApiError::new(
                        capability_execution_error::Code::Backpressure,
                        "failed to reserve the bounded stream terminal slot",
                    ),
                    stream_reason::BACKPRESSURE,
                );
            }
        };
        let guard = self.register_operation();
        let service = self.clone();
        let token = Arc::clone(&guard.token);
        let filter_payload = request
            .filter
            .map(|filter| filter.value)
            .unwrap_or_default();
        let capability = request.capability;
        let public_subscription_id = subscription_id;
        let task_guard = self.start_task();
        tokio::task::spawn_blocking(move || {
            let _guard = guard;
            let _task_guard = task_guard;
            service.run_subscription(SubscriptionTask {
                public_subscription_id,
                capability,
                execution,
                filter_payload,
                ack_timeout,
                token,
                sender,
                terminal_permit,
            });
        });
        Box::pin(ReceiverStream::new(receiver))
    }

    fn run_subscription(&self, task: SubscriptionTask) {
        let SubscriptionTask {
            public_subscription_id,
            capability,
            execution,
            filter_payload,
            ack_timeout,
            token,
            sender,
            terminal_permit,
        } = task;
        let mut terminal_permit = Some(terminal_permit);
        let stream_context = StreamEndContext {
            subscription_id: public_subscription_id.clone(),
            capability: capability.clone(),
            source_id: execution.source_id.clone(),
            binding_id: execution.binding_id.clone().unwrap_or_default(),
        };
        let mut client = match CapabilityWorkerActivator::activate_from_manifest(
            &execution.manifest,
            &execution.worker_options,
        ) {
            Ok(client) => client,
            Err(error) => {
                let api_error = ApiError::from_worker(error);
                let reason = stream_reason_for_error(api_error.code);
                send_terminal(
                    &mut terminal_permit,
                    stream_context.item(
                        0,
                        reason,
                        api_error.message.clone(),
                        Some(api_error.into_wire()),
                    ),
                );
                return;
            }
        };

        let caller_disconnected = sender.is_closed();
        if token.is_cancelled() || caller_disconnected {
            let stopping = self.stopping.load(Ordering::SeqCst);
            let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
            if caller_disconnected {
                return;
            }
            send_terminal(
                &mut terminal_permit,
                stream_context.item(
                    1,
                    if stopping {
                        stream_reason::NORMAL_COMPLETION
                    } else {
                        stream_reason::CANCELLED
                    },
                    if stopping {
                        "capability execution service shutting down"
                    } else {
                        "subscription cancelled before activation completed"
                    },
                    (!stopping).then(|| {
                        ApiError::new(
                            capability_execution_error::Code::Cancelled,
                            "subscription cancelled",
                        )
                        .into_wire()
                    }),
                ),
            );
            return;
        }

        let subscription = match client.subscribe_application_events_with_cancellation(
            &capability,
            &filter_payload,
            self.config.application_event_buffer_capacity,
            ack_timeout,
            token.as_ref(),
        ) {
            Ok(subscription) => subscription,
            Err(error) => {
                if sender.is_closed() {
                    let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                    return;
                }
                let api_error = ApiError::from_worker(error);
                let stopping = self.stopping.load(Ordering::SeqCst);
                let service_shutdown =
                    stopping && api_error.code == capability_execution_error::Code::Cancelled;
                send_terminal(
                    &mut terminal_permit,
                    stream_context.item(
                        if service_shutdown { 1 } else { 0 },
                        if service_shutdown {
                            stream_reason::NORMAL_COMPLETION
                        } else {
                            stream_reason_for_error(api_error.code)
                        },
                        if service_shutdown {
                            "capability execution service shutting down".to_string()
                        } else {
                            api_error.message.clone()
                        },
                        if service_shutdown {
                            None
                        } else {
                            Some(api_error.into_wire())
                        },
                    ),
                );
                let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                return;
            }
        };
        let mut last_generation = 1;

        loop {
            if sender.is_closed() {
                let _ =
                    subscription.unsubscribe(&mut client, self.config.cancellation_drain_timeout);
                let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                return;
            }

            if token.is_cancelled() {
                if self.stopping.load(Ordering::SeqCst) {
                    let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                    send_terminal(
                        &mut terminal_permit,
                        stream_context.item(
                            last_generation,
                            stream_reason::NORMAL_COMPLETION,
                            "capability execution service shutting down",
                            None,
                        ),
                    );
                } else {
                    let _ = subscription
                        .unsubscribe(&mut client, self.config.cancellation_drain_timeout);
                    let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                    send_terminal(
                        &mut terminal_permit,
                        stream_context.item(
                            last_generation,
                            stream_reason::CANCELLED,
                            "subscription cancelled by the gRPC caller",
                            Some(
                                ApiError::new(
                                    capability_execution_error::Code::Cancelled,
                                    "subscription cancelled",
                                )
                                .into_wire(),
                            ),
                        ),
                    );
                }
                return;
            }

            match subscription.next(self.config.event_poll_interval) {
                Ok(event) => {
                    last_generation = event.generation;
                    let item = event_item(
                        &public_subscription_id,
                        execution.binding_id.as_deref(),
                        event,
                    );
                    match sender.try_send(Ok(item)) {
                        Ok(()) => {}
                        Err(TrySendError::Full(_)) => {
                            let _ = subscription
                                .unsubscribe(&mut client, self.config.cancellation_drain_timeout);
                            let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                            send_terminal(
                                &mut terminal_permit,
                                stream_context.item(
                                    last_generation,
                                    stream_reason::BACKPRESSURE,
                                    "bounded capability-event stream buffer is full",
                                    Some(
                                        ApiError::new(
                                            capability_execution_error::Code::Backpressure,
                                            "bounded capability-event stream buffer is full",
                                        )
                                        .into_wire(),
                                    ),
                                ),
                            );
                            return;
                        }
                        Err(TrySendError::Closed(_)) => {
                            let _ = subscription
                                .unsubscribe(&mut client, self.config.cancellation_drain_timeout);
                            let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                            return;
                        }
                    }
                }
                Err(ApplicationEventError::Timeout(_)) => continue,
                Err(ApplicationEventError::Terminated(termination)) => {
                    // Service shutdown owns the process-wide graceful-drain
                    // outcome. If a worker Cancelled terminal races with the
                    // shutdown request, do not leak that internal race as a
                    // caller cancellation.
                    let (generation, reason, message, error) =
                        if self.stopping.load(Ordering::SeqCst) {
                            (
                                last_generation.max(termination.generation),
                                stream_reason::NORMAL_COMPLETION,
                                "capability execution service shutting down".to_string(),
                                None,
                            )
                        } else {
                            let (reason, error) = stream_end_from_termination(&termination);
                            (termination.generation, reason, termination.message, error)
                        };
                    send_terminal(
                        &mut terminal_permit,
                        stream_context.item(generation, reason, message, error),
                    );
                    let _ = client.shutdown(execution.worker_options.shutdown_grace_period);
                    return;
                }
            }
        }
    }
}

#[tonic::async_trait]
impl CapabilityExecutionServiceTrait for CapabilityExecutionService {
    type SubscribeCapabilityEventsStream = CapabilityEventStream;

    async fn invoke_capability(
        &self,
        request: Request<InvokeCapabilityRequest>,
    ) -> Result<Response<InvokeCapabilityResponse>, Status> {
        let metadata = request.metadata().clone();
        Ok(Response::new(
            self.invoke_internal(request.into_inner(), &metadata).await,
        ))
    }

    async fn subscribe_capability_events(
        &self,
        request: Request<SubscribeCapabilityEventsRequest>,
    ) -> Result<Response<Self::SubscribeCapabilityEventsStream>, Status> {
        let metadata = request.metadata().clone();
        Ok(Response::new(
            self.start_subscription(request.into_inner(), &metadata),
        ))
    }
}

/// Convenience constructor for a tonic server registration.
pub fn server(
    service: CapabilityExecutionService,
) -> CapabilityExecutionServiceServer<CapabilityExecutionService> {
    CapabilityExecutionServiceServer::new(service)
}

#[derive(Debug, Clone)]
struct ApiError {
    code: capability_execution_error::Code,
    message: String,
}

impl ApiError {
    fn new(code: capability_execution_error::Code, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }

    fn into_wire(self) -> CapabilityExecutionError {
        CapabilityExecutionError {
            code: self.code as i32,
            message: self.message,
        }
    }

    fn from_worker(error: WorkerTerminalError) -> Self {
        let code = match error {
            WorkerTerminalError::WorkerUnavailable(_) => {
                capability_execution_error::Code::CapabilityUnavailable
            }
            WorkerTerminalError::ActivationFailed(_) => {
                capability_execution_error::Code::ActivationFailed
            }
            WorkerTerminalError::ProtocolMismatch(_) => {
                capability_execution_error::Code::ProtocolMismatch
            }
            WorkerTerminalError::InvalidRequest(_) => {
                capability_execution_error::Code::InvalidRequest
            }
            WorkerTerminalError::CapabilityExecutionFailure(_) => {
                capability_execution_error::Code::ExecutionFailure
            }
            WorkerTerminalError::WorkerCrashed(_) => {
                capability_execution_error::Code::WorkerCrashed
            }
            WorkerTerminalError::Timeout(_) => capability_execution_error::Code::Timeout,
            WorkerTerminalError::Cancelled(_) => capability_execution_error::Code::Cancelled,
        };
        Self::new(code, error.to_string())
    }

    fn from_resolution(error: CapabilityResolutionError) -> Self {
        let code = match error {
            CapabilityResolutionError::NoProvider { .. }
            | CapabilityResolutionError::UnknownBinding { .. }
            | CapabilityResolutionError::BindingProviderUnavailable { .. } => {
                capability_execution_error::Code::CapabilityUnavailable
            }
            CapabilityResolutionError::InterfaceMismatch { .. }
            | CapabilityResolutionError::ExecutionModeMismatch { .. }
            | CapabilityResolutionError::BindingCapabilityMismatch { .. }
            | CapabilityResolutionError::AmbiguousBinding { .. } => {
                capability_execution_error::Code::InvalidRequest
            }
            CapabilityResolutionError::InvalidManifest { .. }
            | CapabilityResolutionError::InvalidBinding { .. }
            | CapabilityResolutionError::DuplicateManifest { .. }
            | CapabilityResolutionError::DuplicateBinding { .. } => {
                capability_execution_error::Code::ActivationFailed
            }
        };
        Self::new(code, error.to_string())
    }
}

fn parse_grpc_timeout(metadata: &MetadataMap) -> Result<Option<Duration>, String> {
    let Some(value) = metadata.get("grpc-timeout") else {
        return Ok(None);
    };
    let raw = value
        .to_str()
        .map_err(|_| "grpc-timeout metadata is not ASCII".to_string())?;
    if raw.len() < 2 || raw.len() > 9 {
        return Err("grpc-timeout metadata has invalid length".into());
    }
    let (digits, unit) = raw.split_at(raw.len() - 1);
    if digits.len() > 8 || digits.is_empty() {
        return Err("grpc-timeout value must contain at most eight digits".into());
    }
    let value = digits
        .parse::<u64>()
        .map_err(|_| "grpc-timeout value must be an unsigned integer".to_string())?;
    let duration = match unit {
        "H" => Duration::from_secs(value.saturating_mul(60 * 60)),
        "M" => Duration::from_secs(value.saturating_mul(60)),
        "S" => Duration::from_secs(value),
        "m" => Duration::from_millis(value),
        "u" => Duration::from_micros(value),
        "n" => Duration::from_nanos(value),
        _ => return Err("grpc-timeout metadata has an unsupported unit".into()),
    };
    Ok(Some(duration))
}

fn response_any(capability: &str, method: &str, result: WorkerInvocationResult) -> Any {
    let type_url = if result.payload_type_url.trim().is_empty() {
        format!("type.cyrene.io/capability/{capability}/{method}/response")
    } else {
        result.payload_type_url
    };
    Any {
        type_url,
        value: result.payload,
    }
}

fn event_any(value: Vec<u8>, type_url: String) -> Any {
    Any {
        type_url: if type_url.trim().is_empty() {
            OPAQUE_PAYLOAD_TYPE_URL.to_string()
        } else {
            type_url
        },
        value,
    }
}

fn event_item(
    public_subscription_id: &str,
    binding_id: Option<&str>,
    event: WorkerApplicationEvent,
) -> CapabilityEventStreamItem {
    CapabilityEventStreamItem {
        item: Some(capability_event_stream_item::Item::ApplicationEvent(
            CapabilityApplicationEvent {
                subscription_id: public_subscription_id.to_string(),
                capability: event.capability,
                event_sequence: event.event_sequence,
                event_type: event.event_type,
                payload: Some(event_any(event.payload, event.payload_type_url)),
                generation: event.generation,
                source_id: event.source_id,
                binding_id: binding_id.unwrap_or_default().to_string(),
            },
        )),
    }
}

impl StreamEndContext {
    fn item(
        &self,
        generation: u64,
        reason: i32,
        message: impl Into<String>,
        error: Option<CapabilityExecutionError>,
    ) -> CapabilityEventStreamItem {
        CapabilityEventStreamItem {
            item: Some(capability_event_stream_item::Item::StreamEnd(
                CapabilityEventStreamEnd {
                    subscription_id: self.subscription_id.clone(),
                    capability: self.capability.clone(),
                    generation,
                    source_id: self.source_id.clone(),
                    binding_id: self.binding_id.clone(),
                    reason,
                    message: message.into(),
                    error,
                },
            )),
        }
    }
}

fn send_terminal(
    permit: &mut Option<OwnedPermit<Result<CapabilityEventStreamItem, Status>>>,
    item: CapabilityEventStreamItem,
) {
    if let Some(permit) = permit.take() {
        permit.send(Ok(item));
    }
}

fn stream_end_from_termination(
    termination: &ApplicationEventStreamTermination,
) -> (i32, Option<CapabilityExecutionError>) {
    let (reason, error_code) = match termination.reason {
        ApplicationEventStreamEndReason::NormalCompletion => {
            (stream_reason::NORMAL_COMPLETION, None)
        }
        ApplicationEventStreamEndReason::Cancelled => (
            stream_reason::CANCELLED,
            Some(capability_execution_error::Code::Cancelled),
        ),
        ApplicationEventStreamEndReason::WorkerUnavailable => (
            stream_reason::CAPABILITY_UNAVAILABLE,
            Some(capability_execution_error::Code::CapabilityUnavailable),
        ),
        ApplicationEventStreamEndReason::WorkerCrash => (
            stream_reason::WORKER_CRASH,
            Some(capability_execution_error::Code::WorkerCrashed),
        ),
        ApplicationEventStreamEndReason::ProtocolFailure => (
            stream_reason::PROTOCOL_FAILURE,
            Some(capability_execution_error::Code::ProtocolMismatch),
        ),
        ApplicationEventStreamEndReason::GenerationTerminated => (
            stream_reason::GENERATION_TERMINATED,
            Some(capability_execution_error::Code::GenerationTerminated),
        ),
        ApplicationEventStreamEndReason::Backpressure => (
            stream_reason::BACKPRESSURE,
            Some(capability_execution_error::Code::Backpressure),
        ),
    };
    (
        reason,
        error_code.map(|code| ApiError::new(code, termination.message.clone()).into_wire()),
    )
}

fn stream_reason_for_error(code: capability_execution_error::Code) -> i32 {
    match code {
        capability_execution_error::Code::CapabilityUnavailable
        | capability_execution_error::Code::ActivationFailed => {
            stream_reason::CAPABILITY_UNAVAILABLE
        }
        capability_execution_error::Code::ProtocolMismatch => stream_reason::PROTOCOL_FAILURE,
        capability_execution_error::Code::WorkerCrashed => stream_reason::WORKER_CRASH,
        capability_execution_error::Code::Cancelled => stream_reason::CANCELLED,
        capability_execution_error::Code::Backpressure => stream_reason::BACKPRESSURE,
        capability_execution_error::Code::GenerationTerminated => {
            stream_reason::GENERATION_TERMINATED
        }
        capability_execution_error::Code::Unspecified
        | capability_execution_error::Code::InvalidRequest
        | capability_execution_error::Code::ExecutionFailure
        | capability_execution_error::Code::Timeout
        | capability_execution_error::Code::StreamTerminated => stream_reason::UNSPECIFIED,
    }
}

mod stream_reason {
    pub const UNSPECIFIED: i32 = 0;
    pub const NORMAL_COMPLETION: i32 = 1;
    pub const CANCELLED: i32 = 2;
    pub const CAPABILITY_UNAVAILABLE: i32 = 3;
    pub const WORKER_CRASH: i32 = 4;
    pub const PROTOCOL_FAILURE: i32 = 5;
    pub const GENERATION_TERMINATED: i32 = 6;
    pub const BACKPRESSURE: i32 = 7;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn grpc_timeout_parser_accepts_native_units() {
        let mut metadata = MetadataMap::new();
        metadata.insert("grpc-timeout", "150m".parse().unwrap());
        assert_eq!(
            parse_grpc_timeout(&metadata).unwrap(),
            Some(Duration::from_millis(150))
        );
    }

    #[test]
    fn event_end_is_a_distinct_oneof_item() {
        let context = StreamEndContext {
            subscription_id: "subscription".into(),
            capability: "capability".into(),
            source_id: "source".into(),
            binding_id: "binding".into(),
        };
        let item = context.item(
            4,
            stream_reason::GENERATION_TERMINATED,
            "generation changed",
            None,
        );
        assert!(matches!(
            item.item,
            Some(capability_event_stream_item::Item::StreamEnd(_))
        ));
    }

    #[test]
    fn configured_binding_identity_is_independent_from_runtime_generation() {
        let event = |generation| {
            event_item(
                "subscription",
                Some("configured-main"),
                WorkerApplicationEvent {
                    subscription_id: "worker-subscription".to_string(),
                    capability: "capability.v1".to_string(),
                    event_sequence: 1,
                    event_type: "event".to_string(),
                    payload: Vec::new(),
                    payload_type_url: String::new(),
                    generation,
                    source_id: "provider".to_string(),
                },
            )
        };

        let first = event(1);
        let second = event(2);
        let Some(capability_event_stream_item::Item::ApplicationEvent(first)) = first.item else {
            panic!("expected application event");
        };
        let Some(capability_event_stream_item::Item::ApplicationEvent(second)) = second.item else {
            panic!("expected application event");
        };
        assert_eq!(first.binding_id, "configured-main");
        assert_eq!(second.binding_id, "configured-main");
        assert_eq!(first.generation, 1);
        assert_eq!(second.generation, 2);
    }

    #[test]
    fn typed_worker_response_preserves_capability_owned_any_type_url() {
        let response = response_any(
            "message.connector.v1",
            "send_message",
            WorkerInvocationResult {
                payload: vec![1, 2, 3],
                payload_type_url: "type.googleapis.com/cyrene.message.connector.v1.DeliveryResult"
                    .into(),
            },
        );

        assert_eq!(
            response.type_url,
            "type.googleapis.com/cyrene.message.connector.v1.DeliveryResult"
        );
        assert_eq!(response.value, vec![1, 2, 3]);
    }

    #[test]
    fn legacy_worker_response_without_type_url_keeps_generic_projection() {
        let response = response_any(
            "test.capability.v1",
            "echo",
            WorkerInvocationResult {
                payload: vec![4, 5],
                payload_type_url: String::new(),
            },
        );

        assert_eq!(
            response.type_url,
            "type.cyrene.io/capability/test.capability.v1/echo/response"
        );
    }

    #[test]
    fn service_config_enforces_the_platform_buffer_hard_maximum() {
        let service = CapabilityExecutionService::new(
            CapabilityRegistry::new(),
            CapabilityExecutionConfig {
                application_event_buffer_capacity: MAX_APPLICATION_EVENT_BUFFER_CAPACITY + 1,
                ..CapabilityExecutionConfig::default()
            },
        );
        assert_eq!(
            service.configured_event_buffer_capacity(),
            MAX_APPLICATION_EVENT_BUFFER_CAPACITY
        );
    }
}
